name: Build and Deploy Angular App

on:
  push:
    branches:
      - main   # Run only when code is pushed to main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js (Angular 16 works best with Node 18/20)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build Angular project (production mode)
      - name: Build Angular
        run: npm run build -- --configuration production

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/NG.com   # ⚡ Replace with your Angular dist folder name
